export const SHIPPING_ZONE_KEYS = {
  YANGON: "YANGON",
  MANDALAY: "MANDALAY",
  PYINMANA: "PYINMANA",
  NAY_PYI_DAW: "NAY_PYI_DAW",
  OTHER_MYANMAR: "OTHER_MYANMAR",
} as const;

export const SHIPPING_ZONE_LABELS: Record<string, string> = {
  [SHIPPING_ZONE_KEYS.YANGON]: "Yangon",
  [SHIPPING_ZONE_KEYS.MANDALAY]: "Mandalay",
  [SHIPPING_ZONE_KEYS.PYINMANA]: "Pyinmana",
  [SHIPPING_ZONE_KEYS.NAY_PYI_DAW]: "Nay Pyi Daw",
  [SHIPPING_ZONE_KEYS.OTHER_MYANMAR]: "Other (Myanmar)",
};

export const PRIORITY_SHIPPING_ZONE_KEYS = [
  SHIPPING_ZONE_KEYS.YANGON,
  SHIPPING_ZONE_KEYS.MANDALAY,
  SHIPPING_ZONE_KEYS.PYINMANA,
  SHIPPING_ZONE_KEYS.NAY_PYI_DAW,
] as const;

export const FALLBACK_SHIPPING_ZONE_KEY = SHIPPING_ZONE_KEYS.OTHER_MYANMAR;
