export const ADMIN_CATALOG_COPY = {
  upload: {
    signUploadFailed: "Could not prepare upload. Please retry.",
    uploadFailedFallback: "Direct upload failed. Trying fallback upload failed too.",
    uploadNetworkError: "Network error while uploading. Check your connection and retry.",
    invalidFileType: "Unsupported file type. Use JPG, PNG, WEBP, or AVIF.",
    fileTooLarge: "File is too large. Maximum is 8MB.",
    genericUploadFailed: "Upload failed. Try again.",
    uploadedToR2: "Image uploaded to R2.",
    failedToPrepareUpload: "Failed to prepare upload.",
    failedToUploadImage: "Failed to upload image.",
    unexpectedUploadingImage: "Unexpected error while uploading image.",
    noPreview: "No Preview",
    dragToReorder: "Drag image cards to reorder. First image is used as primary.",
    uploadToPreview: "Upload a file to preview this image.",
  },
  load: {
    loadCatalogFailed: "Failed to load catalog.",
    loadProductDetailsFailed: "Failed to load product details.",
    unexpectedLoadProductDetails: "Unexpected error while loading product details.",
    retryLabel: "Retry",
  },
  draftValidation: {
    failedValidateDraft: "Failed to validate product draft.",
    fixBeforeCreate: "Fix draft issues before creating this product.",
    fixBeforeSave: "Fix draft issues before saving this product.",
  },
  create: {
    failedCreate: "Failed to create product.",
    unexpectedCreate: "Unexpected error while creating product.",
    createdAndPublished: (name: string) => `Created and published product ${name}.`,
    createdDraft: (name: string) => `Created draft product ${name}.`,
  },
  update: {
    failedUpdate: "Failed to update product.",
    unexpectedUpdate: "Unexpected error while updating product.",
    updatedAndPublished: (name: string) => `Updated and published product ${name}.`,
    savedDraft: (name: string) => `Saved draft for ${name}.`,
  },
  inventory: {
    quantityDeltaZero: "Quantity delta must not be zero.",
    noteRequired: "Please add an inventory adjustment note (at least 4 characters).",
    failedAdjustInventory: "Failed to adjust inventory.",
    unexpectedAdjustInventory: "Unexpected error while adjusting inventory.",
    inventoryUpdated: (sku: string) => `Inventory updated for ${sku}.`,
  },
  category: {
    failedCreate: "Failed to create category.",
    unexpectedCreate: "Unexpected error while creating category.",
  },
  matrix: {
    failedGenerate: "Failed to generate variant matrix.",
    unexpectedGenerate: "Unexpected error while generating variants.",
  },
  wizard: {
    createProductTitle: "Create Product",
    reviewTitle: "Review Before Save",
    jumpToFix: "Jump to fix",
    reviewHint: "Use Save Draft to keep work-in-progress, or Publish to set product status ACTIVE.",
  },
  bulkActions: {
    selectAll: "Select All",
    clear: "Clear",
    applyBulkChanges: "Apply Bulk Changes",
    autofillNameSku: "Auto-fill Name/SKU",
    duplicateSelected: "Duplicate Selected",
    normalizeSortOrder: "Normalize Sort Order",
    removeSelected: "Remove Selected",
    clearCompleted: "Clear Completed",
  },
} as const;
